services:
  postgres:
    image: postgres:16-alpine
    container_name: papel_recriado_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: papel_recriado
      POSTGRES_PASSWORD: papel_recriado_123
      POSTGRES_DB: papel_recriado
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
